sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t mkj2393/docker-reach-app -f Dockerfile.dev .

script:
  - docker run -e CI=true mkj2393/docker-reach-app npm run  test -- --coverage

after_success:
  - echo "Test success"